import { mkdirSync, readFileSync, writeFileSync } from "node:fs"; import { dirname, join } from "node:path"; export const SAND_GROUP_FILENAME = "group.json"; export const GROUP_CONFIG_VERSION = 1; export const GROUP_MAX_MEMBERS = 6; export interface RemoteGroupMember { ownerAuthId: string; agentId: string; name: string; avatarDataUrl?: string } export interface SandGroupConfig { version: number; memberIds: string[]; remoteMembers?: RemoteGroupMember[]; sharedRoomId?: string }
export function getSandGroupPath(agentDir: string): string { return join(agentDir, SAND_GROUP_FILENAME); } export function normalizeMemberIds(raw: unknown): string[] { if (!Array.isArray(raw)) return []; const seen = new Set<string>(); for (const value of raw) { if (typeof value !== "string") continue; const id = value.trim(); if (!id || seen.has(id)) continue; seen.add(id); if (seen.size >= GROUP_MAX_MEMBERS) break; } return [...seen]; }
export function normalizeRemoteMembers(raw: unknown): RemoteGroupMember[] { if (!Array.isArray(raw)) return []; const seen = new Set<string>(), members: RemoteGroupMember[] = []; for (const value of raw) { if (typeof value !== "object" || value == null) continue; const candidate = value as Record<string, unknown>; if (typeof candidate.ownerAuthId !== "string" || typeof candidate.agentId !== "string") continue; const ownerAuthId = candidate.ownerAuthId.trim(), agentId = candidate.agentId.trim(), key = `${ownerAuthId}\0${agentId}`; if (!ownerAuthId || !agentId || seen.has(key)) continue; seen.add(key); members.push({ ownerAuthId, agentId, name: typeof candidate.name === "string" && candidate.name.trim() ? candidate.name.trim() : "Agent", ...(typeof candidate.avatarDataUrl === "string" && candidate.avatarDataUrl ? { avatarDataUrl: candidate.avatarDataUrl } : {}) }); } return members; }
export function capCombinedGroupRoster(memberIds: readonly string[], remoteMembers: readonly RemoteGroupMember[] = []): { memberIds: string[]; remoteMembers: RemoteGroupMember[] } {
  const locals = normalizeMemberIds(memberIds);
  const remotes = normalizeRemoteMembers(remoteMembers);
  const keptLocal: string[] = [];
  const keptRemote: RemoteGroupMember[] = [];
  let remaining = GROUP_MAX_MEMBERS;
  for (const id of locals) { if (remaining <= 0) break; keptLocal.push(id); remaining -= 1; }
  for (const member of remotes) { if (remaining <= 0) break; keptRemote.push(member); remaining -= 1; }
  return { memberIds: keptLocal, remoteMembers: keptRemote };
}
export function readSandGroupConfig(agentDir: string): SandGroupConfig | null { let parsed: Record<string, unknown>; try { parsed = JSON.parse(readFileSync(getSandGroupPath(agentDir), "utf8")); } catch { return null; } if (typeof parsed !== "object" || parsed == null) return null; const roster = capCombinedGroupRoster(normalizeMemberIds(parsed.memberIds), normalizeRemoteMembers(parsed.remoteMembers)), sharedRoomId = typeof parsed.sharedRoomId === "string" && parsed.sharedRoomId.length > 0 ? parsed.sharedRoomId : undefined; if (roster.memberIds.length === 0 && roster.remoteMembers.length === 0 && sharedRoomId === undefined) return null; return { version: typeof parsed.version === "number" ? parsed.version : GROUP_CONFIG_VERSION, memberIds: roster.memberIds, ...(roster.remoteMembers.length > 0 ? { remoteMembers: roster.remoteMembers } : {}), ...(sharedRoomId === undefined ? {} : { sharedRoomId }) }; }
export function writeSandGroupConfig(agentDir: string, config: SandGroupConfig): void { const path = getSandGroupPath(agentDir); mkdirSync(dirname(path), { recursive: true }); const roster = capCombinedGroupRoster(config.memberIds, config.remoteMembers ?? []); writeFileSync(path, `${JSON.stringify({ version: config.version, memberIds: roster.memberIds, ...(roster.remoteMembers.length > 0 ? { remoteMembers: roster.remoteMembers } : {}), ...(config.sharedRoomId ? { sharedRoomId: config.sharedRoomId } : {}) }, null, 2)}\n`, "utf8"); } export function isSandGroupDir(agentDir: string): boolean { return readSandGroupConfig(agentDir) != null; }
